### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by jjjrmy** [seancheung/history#10]
vagrant@homestead:~/liveleads$ composer require panoscape/history
    1/3:        http://repo.packagist.org/p/provider-latest$7f656255e7b2a5283b4f27a1f319e64352efcbf29ab8d197e8ca2f18cd7d92c6.json
    2/3:        http://repo.packagist.org/p/provider-2020-04$6b12b12e0eb343a930029e1aad1525f979721416cf17744b20fcc4ccbd2342b4.json
    3/3:        http://repo.packagist.org/p/provider-2020-01$ae3a8c17fbb9e4c9ae542510759e90db46063180e5910612980d38d8c13258cc.json
    Finished: success: 3, skipped: 0, failure: 0, total: 3                                                                                                                                   Using version ^1.0 for panoscape/history                  
./composer.json has been updated
Loading composer repositories with package information                                                                                                                                           Updating dependencies (including require-dev)         
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install laravel/framework v7.11.0
    - Conclusion: don't install laravel/framework 7.x-dev
    - Conclusion: remove dropoutventures/laravel-address-validation dev-master
    - Conclusion: don't install dropoutventures/laravel-address-validation dev-master
    - Installation request for laravel/framework (locked at v7.9.2, required as ^7.0) -> satisfiable by laravel/framework[v7.9.2].
    - Installation request for dropoutventures/laravel-address-validation dev-master -> satisfiable by dropoutventures/laravel-address-validation[dev-master].
    - Conclusion: don't install illuminate/support v7.11.0
    - dropoutventures/laravel-address-validation dev-master requires laravel/framework ^7.0 -> satisfiable by laravel/framework[v7.9.2, 7.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.10.0, v7.10.1, v7.10.2, v7.10.3, v7.11.0, v7.2.0, v7.2.1, v7.2.2, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.6.1, v7.6.2, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1].
    - don't install laravel/framework v7.0.0|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.0.1|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.0.2|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.0.3|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.0.4|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.0.5|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.0.6|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.0.7|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.0.8|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.1.0|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.1.1|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.1.2|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.1.3|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.10.0|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.10.1|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.10.2|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.10.3|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.2.0|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.2.1|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.2.2|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.3.0|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.4.0|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.5.0|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.5.1|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.5.2|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.6.0|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.6.1|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.6.2|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.7.0|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.7.1|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.8.0|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.8.1|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.9.0|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.9.1|don't install illuminate/support 7.x-dev
    - don't install laravel/framework v7.9.2|don't install illuminate/support 7.x-dev
    - don't install illuminate/support 7.x-dev|remove laravel/framework v7.9.2
    - don't install illuminate/support 7.x-dev|don't install laravel/framework v7.9.2
    - Installation request for illuminate/support ^7.11 -> satisfiable by illuminate/support[7.x-dev, v7.11.0], laravel/framework[7.x-dev, v7.11.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by seancheung** [comment]
Laravel 7.x incompatible

**Comment by jjjrmy** [comment]
@seancheung Check my PR

**Comment by seancheung** [comment]
Thanks
