### ISSUE TITLE
Skip empty time

### ISSUE THREAD

**Issue by howdu** [seancheung/history#27]
Is it possible to ignore certain changes? Eg:
`[{"key":"published_at","old":"2022-11-10 00:00:00","new":"2022-11-10"}]`

**Comment by seancheung** [comment]
It would be a new feature to support custom meta value filters. Marked.

At the moment you can override the trait to do the filtering as described in [custom-meta](https://github.com/seancheung/history#custom-meta) (Return `null` will skip tracking)
