### ISSUE TITLE
Sorting model history

### ISSUE THREAD

**Issue by milukove** [seancheung/history#3]
Hi! I like this extension in my project, you doing great job, thank you.

Please, help me finding a simple way to set asc/desc ordering by "performed_at" attribute on history rendering?

**Comment by seancheung** [comment]
Once you have added `HasHistories` trait to your target model and `HasOperations` to your source model, you are able to fetch histories/operations from these models.

For target model(the model an action performed on): 
```php
$target_model->histories
```
For source model(the model an action performed by): 
```php
$source_model->operations
```
Both of them return Eloquent relationships which also serve as query builders. You can add further constraints by chaining conditions:
```php
$target_model->histories()->orderBy('performed_at', 'desc')->take(10)
```
The above example takes the latest ten records.

**Comment by seancheung** [comment]
Readme updated with query help:

[Additional query conditions](https://github.com/seancheung/history#additional-query-conditions)
