### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by dongfang** [seancheung/history#30]
Can Laravel 10 support be added? Missing that.

**Comment by mhusseinsaad** [comment]
+1

**Comment by wrtisans** [comment]
+1

**Comment by seancheung** [comment]
Thank you guys. A new release has been published.
Checkout [v2.5.0](../releases/tag/2.5.0)

**Comment by KarimGeiger** [comment]
Thank you for your continued support in keeping the project up to date, @seancheung! We appreciate it.
