### ISSUE TITLE
HistoryOserver isIgnored blacklist test

### ISSUE THREAD

**Issue by tcharod** [seancheung/history#7]
When testing the existence of the model in the blacklist, 

> panoscape/history/src/HistoryObserver.php, line 114; 

the index name (**$array = $blacklist [$name];**) does not exist during an updating event.

So I change this statement to `$array = isset($blacklist [$name]) ? $blacklist[$name] : []`;

**Comment by trangunghoa** [comment]
I also got this error. The reason is attributes_blacklist on history.php are not allows null. we should use your code to fix it.

**Comment by seancheung** [comment]
Check the latest release
