### ISSUE TITLE
Is there a simple option to pass custom message?

### ISSUE THREAD

**Issue by anshad** [seancheung/history#8]
Is there a simple option to pass custom message on different model activities?

**Comment by seancheung** [comment]
Please check [Custom History](../../history#custom-history)

For built-in events(CRUD), there is no way to specify the fired event's `meta` field. For an `update` event, its `meta` will always be the changed properties map. For other standard events, `meta` will always be `null`. 

For a custom event, the content of its `meta` field is up to you.

e.g.
```php
use Panoscape\History\Events\ModelChanged;
event(new ModelChanged($model, 'Something vital happened', [ ['remarks' => "It's important"] ]));
```
